name: Build and deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      MYSQL_URL: ${{ vars.MYSQL_URL }}
      MYSQL_USER: ${{ vars.MYSQL_USER }}
      MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ASSEMBLY_AI_SECRET: ${{ secrets.ASSEMBLY_AI_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Rewrite ENVIRONMENT to prod
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application.properties"
          property: "spring.profiles.active"
          value: "prod"

      - name: Rewrite MYSQL_PASS
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application-prod.properties"
          property: "spring.datasource.password"
          value: "${{ secrets.MYSQL_PASS }}"

      - name: Rewrite JWT_SECRET
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application-prod.properties"
          property: "jwt.secret"
          value: "${{ secrets.JWT_SECRET }}"

      - name: Rewrite ASSEMBLY_AI_SECRET
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application-prod.properties"
          property: "assemblyAi.secret"
          value: "${{ secrets.ASSEMBLY_AI_SECRET }}"

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.jar"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B3358D8E3A54787A4466842AF3544B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D74B1888B1F479481DD9C24EA92BA96 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3489BCCF94D4138AC246BB5157B27C2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'back-lecti'
          slot-name: 'Production'
          package: '*.jar'
          