name: Build and run tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      MYSQL_URL: ${{ vars.MYSQL_URL }}
      MYSQL_USER: ${{ vars.MYSQL_USER }}
      MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Rewrite ENVIRONMENT to prod
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application.properties"
          property: "spring.profiles.active"
          value: "prod"

      - name: Rewrite MYSQL_PASS
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application-prod.properties"
          property: "spring.datasource.password"
          value: "${{ secrets.MYSQL_PASS }}"

      - name: Rewrite JWT_SECRET
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: "./src/main/resources/application-prod.properties"
          property: "jwt.secret"
          value: "${{ secrets.JWT_SECRET }}"

      - name: Build with Maven
        run: mvn package --file pom.xml
